extension_dir=/usr/lib64/php/modules
memory_limit=512M
max_execution_time=600
display_errors=1
log_errors=1
curl.cainfo=/dockan/rootfs/app/.dockan/tls-ca-bundle.pem
openssl.cafile=/dockan/rootfs/app/.dockan/tls-ca-bundle.pem
